# Generated by Django 3.0.3 on 2020-02-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Search_Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('search_video_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('date', models.CharField(max_length=100)),
                ('view_count', models.CharField(max_length=20)),
            ],
        ),
    ]
